<?php

namespace App\Http\Resources\teams;

use Illuminate\Http\Resources\Json\JsonResource;

class TeamStatsResource extends JsonResource
{
    public function toArray($request): array
    {
        return [
            "id"                            => $this->id,
            "goals"                         => (int) $this->goals,
            "goalsConceded"                 => (int) $this->goals_conceded,
            "penaltyGoals"                  => (int) $this->penalty_goals,
            "penaltyAttempts"               => (int) $this->penalty_attempts,
            "freeKickGoals"                 => (int) $this->free_kick_goals,
            "freeKickAttempts"              => (int) $this->free_kick_attempts,
            "goalsInsideBox"                => (int) $this->goals_inside_box,
            "shotsInsideBox"                => (int) $this->shots_inside_box,
            "goalsOutsideBox"               => (int) $this->goals_outside_box,
            "shotsOutsideBox"               => (int) $this->shots_outside_box,
            "leftFootGoals"                 => (int) $this->left_foot_goals,
            "rightFootGoals"                => (int) $this->right_foot_goals,
            "headedGoals"                   => (int) $this->headed_goals,
            "bigChances"                    => (int) $this->big_chances,
            "bigChancesMissed"              => (int) $this->big_chances_missed,
            "shots"                         => (int) $this->shots,
            "shotsOnTarget"                 => (int) $this->shots_on_target,
            "shotsOffTarget"                => (int) $this->shots_off_target,
            "blockedShots"                  => (int) $this->blocked_shots,
            "successfulDribbles"            => (int) $this->successful_dribbles,
            "hitWoodwork"                   => (int) $this->hit_woodwork,
            "counterAttacks"                => (int) $this->counter_attacks,
            "bigChancesCreated"             => (int) $this->big_chances_created,
            "expectedGoals"                 => (float) $this->expected_goals,
            "possession"                    => (float) $this->possession,
            "passesAttempted"               => (int) $this->passes_attempted,
            "passesCompleted"               => (int) $this->passes_completed,
            "ownHalfPassesCompleted"        => (int) $this->own_half_passes_completed,
            "ownHalfPassesAttempted"        => (int) $this->own_half_passes_attempted,
            "oppositionHalfPassesCompleted" => (int) $this->opposition_half_passes_completed,
            "oppositionHalfPassesAttempted" => (int) $this->opposition_half_passes_attempted,
            "longBallsCompleted"            => (int) $this->long_balls_completed,
            "longBallsAttempted"            => (int) $this->long_balls_attempted,
            "crossesCompleted"              => (int) $this->crosses_completed,
            "crossesAttempted"              => (int) $this->crosses_attempted,
            "throughBallsCompleted"         => (int) $this->through_balls_completed,
            "progressivePasses"             => (int) $this->progressive_passes,
            "tackles"                       => (int) $this->tackles,
            "tacklesWon"                    => (int) $this->tackles_won,
            "interceptions"                 => (int) $this->interceptions,
            "clearances"                    => (int) $this->clearances,
            "saves"                         => (int) $this->saves,
            "ballsRecovered"                => (int) $this->balls_recovered,
            "errorsLeadingToShot"           => (int) $this->errors_leading_to_shot,
            "errorsLeadingToGoal"           => (int) $this->errors_leading_to_goal,
            "penaltiesCommitted"            => (int) $this->penalties_committed,
            "penaltyGoalsConceded"          => (int) $this->penalty_goals_conceded,
            "clearancesOffLine"             => (int) $this->clearances_off_line,
            "lastManTackles"                => (int) $this->last_man_tackles,
            "cleanSheet"                    => (int) $this->clean_sheet,
            "duelsTotal"                    => (int) $this->duels_total,
            "duelsWon"                      => (int) $this->duels_won,
            "groundDuelsTotal"              => (int) $this->ground_duels_total,
            "groundDuelsWon"                => (int) $this->ground_duels_won,
            "aerialDuelsWon"                => (int) $this->aerial_duels_won,
            "aerialDuelsTotal"              => (int) $this->aerial_duels_total,
            "possessionLost"                => (int) $this->possession_lost,
            "throwIns"                      => (int) $this->throw_ins,
            "goalKicks"                     => (int) $this->goal_kicks,
            "offsides"                      => (int) $this->offsides,
            "foulsCommitted"                => (int) $this->fouls_committed,
            "foulsSuffered"                 => (int) $this->fouls_suffered,
            "yellowCards"                   => (int) $this->yellow_cards,
            "redCards"                      => (int) $this->red_cards,
            "corners"                       => (int) $this->corners,
            "freeKicks"                     => (int) $this->free_kicks,
        ];
    }
}
